hiqp_joint_velocity_controller:
  #####      JOINT LIMITATIONS    #####
  hiqp_preload_tasks:
    - name: 'jnt1_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link1', '1.0', '2.0', '-2.9', '2.9'] #ddq_max, dq_max, lower link limit, upper joint limit
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt2_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link2', '1.0', '2.0', '-1.8', '1.8']
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt3_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link3', '0.1', '2.0', '-2.9', '2.9']
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt4_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link4', '1.0', '2.0', '-3.1', '0.0']
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt5_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link5', '1.0', '2.0', '-2.9', '2.9']
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt6_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link6', '1.0', '2.0', '-0.05', '3.8']
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt7_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link7', '1.0', '2.0', '-2.9', '2.9']
      dyn_params: ['TDynPD', '0.2', '0.9']

franka_hiqp_joint_effort_controller:
  #####      JOINT LIMITATIONS    #####
  hiqp_preload_tasks:
    - name: 'jnt1_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link1', '1.0', '2.0', '-2.9', '2.9'] #ddq_max, dq_max, lower link limit, upper joint limit
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt2_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link2', '1.0', '2.0', '-1.8', '1.8']
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt3_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link3', '0.1', '2.0', '-2.9', '2.9']
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt4_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link4', '1.0', '2.0', '-3.1', '0.0']
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt5_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link5', '1.0', '2.0', '-2.9', '2.9']
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt6_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link6', '1.0', '2.0', '-0.05', '3.8']
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt7_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link7', '1.0', '2.0', '-2.9', '2.9']
      dyn_params: ['TDynPD', '0.2', '0.9']

hiqp_joint_effort_controller:
  #####      JOINT LIMITATIONS    #####
  hiqp_preload_tasks:
    - name: 'jnt1_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link1', '1.0', '2.0', '-2.9', '2.9'] #ddq_max, dq_max, lower link limit, upper joint limit
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt2_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link2', '1.0', '2.0', '-1.8', '1.8']
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt3_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link3', '0.1', '2.0', '-2.9', '2.9']
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt4_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link4', '1.0', '2.0', '-3.1', '0.0']
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt5_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link5', '1.0', '2.0', '-2.9', '2.9']
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt6_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link6', '1.0', '2.0', '-0.05', '3.8']
      dyn_params: ['TDynPD', '0.2', '0.9']
    - name: 'jnt7_limits'
      priority: 0
      active: true
      monitored: true
      def_params: ['TDefJntLimits','panda_link7', '1.0', '2.0', '-2.9', '2.9']
      dyn_params: ['TDynPD', '0.2', '0.9']